### Goals Endpoints ###

### Get all goals for a user (Local)
GET http://localhost:3000/goals/user/1

### Get all goals for a user (Remote)
GET https://nisa-invest-tfb-be.vercel.app/goals/user/1

### Get goal by goal_id (Local)
GET http://localhost:3000/goals/4

### Get goal by goal_id (Remote)
GET https://nisa-invest-tfb-be.vercel.app/goals/4

### Create goal (Local)
POST http://localhost:3000/goals
Content-Type: application/json

{
    "user_id": 1,
    "title": "New Goal",
    "description": "This is a new goal",
    "status": "not_done",
    "is_recurrent": false,
    "due_date": "2024-12-31T23:59:59Z"
}

### Create goal (Remote)
POST https://nisa-invest-tfb-be.vercel.app/goals
Content-Type: application/json

{
    "user_id": 1,
    "title": "New Goal",
    "description": "This is a new goal",
    "status": "not_done",
    "is_recurrent": false,
    "due_date": "2024-12-31T23:59:59Z"
}

### Update goal (general information) (Local)
PUT http://localhost:3000/goals/1
Content-Type: application/json

{
    "title": "Updated Goal Title2",
    "description": "Updated description",
    "is_recurrent": true,
    "recurrence_type": "week",
    "recurrence_value": 1,
    "category": "fitness"
}

### Update goal (general information) (Remote)
PUT https://nisa-invest-tfb-be.vercel.app/goals/1
Content-Type: application/json

{
    "title": "Updated Goal Title2",
    "description": "Updated description",
    "is_recurrent": true,
    "recurrence_type": "week",
    "recurrence_value": 1,
    "category": "fitness"
}

### Update user-specific goal information (Local)
PUT http://localhost:3000/goals/user-goal/2/1
Content-Type: application/json

{
    "status": "not_done",
    "due_date": "2023-12-31T23:59:59Z"
}

### Update user-specific goal information (Remote)
PUT https://nisa-invest-tfb-be.vercel.app/goals/user-goal/2/1
Content-Type: application/json

{
    "status": "not_done",
    "due_date": "2023-12-31T23:59:59Z"
}

### Delete goal (Local)
DELETE http://localhost:3000/goals/21

### Delete goal (Remote)
DELETE https://nisa-invest-tfb-be.vercel.app/goals/21

### Set goals to true or create if not exist (Local)
POST http://localhost:3000/goals/update-quiz-selected
Content-Type: application/json

{
  "userId": 1,
  "goalIds": [1, 2, 3]
}

### Set goals to true or create if not exist (Remote)
POST https://nisa-invest-tfb-be.vercel.app/goals/update-quiz-selected
Content-Type: application/json

{
  "userId": 5,
  "goalIds": [1, 2, 3]
}

### Focus a goal manually by the user (Local)
PUT http://localhost:3000/goals/user-goal/focus/1/2
Content-Type: application/json

### Focus a goal manually by the user (Remote)
PUT https://nisa-invest-tfb-be.vercel.app/goals/user-goal/focus/1/2
Content-Type: application/json

### Complete a goal manually by the user (Local)
PUT http://localhost:3000/goals/user-goal/complete/1/2
Content-Type: application/json

### Complete a goal manually by the user (Remote)
PUT https://nisa-invest-tfb-be.vercel.app/goals/user-goal/complete/1/2
Content-Type: application/json

# How to use it:
# const userId = 1; // The user ID
# const goalIds = [1, 2, 3]; // The list of goal IDs

# fetch('http://localhost:3000/user-goals/update-quiz-selected', {
#   method: 'POST',
#   headers: {
#     'Content-Type': 'application/json',
#   },
#   body: JSON.stringify({ userId, goalIds }),
# })
#   .then(response => response.json())
#   .then(result => console.log(result))
#   .catch(error => console.error('Error:', error));
