### Quotes Endpoints ###

### Get all quotes (Local)
GET http://localhost:3000/quotes

### Get all quotes (Remote)
GET https://nisa-invest-tfb-be.vercel.app/quotes

### Get quote by id (Local)
GET http://localhost:3000/quotes/10

### Get quote by id (Remote)
GET https://nisa-invest-tfb-be.vercel.app/quotes/10

### Create quote (Local)
POST http://localhost:3000/quotes
Content-Type: application/json

{
    "text": "New inspirational quote",
    "author": "Unknown Author",
    "valid_from": "2023-01-01",
    "valid_to": "2023-12-31"
}

### Create quote (Remote)
POST https://nisa-invest-tfb-be.vercel.app/quotes
Content-Type: application/json

{
    "text": "New inspirational quote",
    "author": "Unknown Author",
    "valid_from": "2023-01-01",
    "valid_to": "2023-12-31"
}

### Update quote (Local)
PUT http://localhost:3000/quotes/1
Content-Type: application/json

{
    "text": "Updated inspirational quote",
    "author": "Known Author"
}

### Update quote (Remote)
PUT https://nisa-invest-tfb-be.vercel.app/quotes/1
Content-Type: application/json

{
    "text": "Updated inspirational quote",
    "author": "Known Author"
}

### Delete quote (Local)
DELETE http://localhost:3000/quotes/1

### Delete quote (Remote)
DELETE https://nisa-invest-tfb-be.vercel.app/quotes/1

### Get random quotes for a specific date (Local)
GET http://localhost:3000/quotes/random?date=2024-04-1&count=3

### Get random quotes for a specific date (Remote)
GET https://nisa-invest-tfb-be.vercel.app/quotes/random?date=2024-04-1&count=3

### Get random quotes for today (Local)
GET http://localhost:3000/quotes/random?count=2

### Get random quotes for today (Remote)
GET https://nisa-invest-tfb-be.vercel.app/quotes/random?count=2